version: '3.7'

services:

  web:
    container_name: weather-off-web-container
    image: weather-off-web-image
    build: .
    command: ./entry/docker-web-off-entry.sh
    volumes:
      - .:/code
      - ./weather-volumes/static:/code/weatherAPI/weatherAPI/static
    expose:
      - 8001
    tty: true
    stdin_open: true
    env_file:
      - .env

  nginx:
    image: nginx:1.17.6-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./weather.conf:/etc/nginx/conf.d/weather.conf
      - ./weather-volumes/logs/nginx:/var/log/nginx
      - ./weather-volumes/static:/code/weatherAPI/weatherAPI/static
    links:
      - web:web
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"