version: '3.7'

services:

  web:
    container_name: weather-web-container
    image: weather-web-image
    build: .
    command: ./entry/docker-web-entry.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env