# Generated by Django 3.1.4 on 2020-12-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('temp', models.IntegerField()),
                ('cond', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'History',
            },
        ),
    ]
