# Generated by Django 3.1.4 on 2020-12-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='cond',
            new_name='describ',
        ),
        migrations.AddField(
            model_name='history',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='maxtp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='mintp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
